spring.application.name=truckage

spring.datasource.url=jdbc:postgresql://localhost:5432/truckage
spring.datasource.username=postgres
spring.datasource.password=123mudar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true